### ISSUE TITLE
Login with Google when multiple Gmail accounts are open in web browsr

### ISSUE THREAD

**Issue by tristanKaplan** [internet4000/radio4000-api#41]
Gentlemen, 

Because I am using several Gmail accounts at the same time, I cannot log-in to R4000 using gmail, the pop up triggered keeps running and nothing happen (see the attached file)

Therefore, the solution is to log-out from all the google accounts and only keep the one I registered to R4000 with... It's doable but not that convinient.

Peace !

![capture d ecran 2018-04-06 a 16 25 46](https://user-images.githubusercontent.com/26389047/38427002-5f176412-39b8-11e8-9e8d-ee5e3c542951.png)

**Comment by hugurp** [comment]
Hi!

Thanks for opening this issue, well spotted!

I believe this issue is not inside the right Github repository, this one is for the API, so the correct one would be for the frontend part of the application: https://github.com/internet4000/radio4000

I will move your issue to the right place, close this one and link it here so you can stay in the loop.

**Comment by hugurp** [comment]
Closing
