### ISSUE TITLE
Add documentation on deployment

### ISSUE THREAD

**Issue by u8887** [internet4000/radio4000-api#42]
How is a project supposed to be deployed so it goes live on https://api.radio4000.com/?

Master version seems to be ready to be deployed, so I merged it in production thinking travis would deploy it after test pass. It does not seem to have happenned.

https://travis-ci.org/internet4000/radio4000-api/branches

**Comment by oskarrough** [comment]
Yes, a commit to the `production` should be all that is needed. I believe the builds on production branch were failing because of cache. I…

1. cleared cache https://travis-ci.org/internet4000/radio4000-api/caches
2. configured travis to build all branches (and not just PR) https://travis-ci.org/internet4000/radio4000-api/settings
3. triggered new deploy via travis interface

Seems to work again?

https://travis-ci.org/internet4000/radio4000-api/builds/375851712

**Comment by u8887** [comment]
Oh nice!
I'll try to open a PR to precise the development doc.
