### ISSUE TITLE
Fix image structure

### ISSUE THREAD

**Issue by oskarrough** [internet4000/radio4000-api#7]
Currently we return an object of images for a channel, firebase-style.

Instead we should return the `imageSrc` from the newest image model a channel has.

**Comment by oskarrough** [comment]
https://github.com/internet4000/radio4000-api/pull/8

**Comment by oskarrough** [comment]
Query for channel thumbnail (last image)

https://radio4000.firebaseio.com/images.json?orderBy=%22channel%22&startAt=%22-JXHtCxC9Ew-Ilck6iZ8%22&endAt=%22-JXHtCxC9Ew-Ilck6iZ8%22&limitToLast=1

**Comment by hugurp** [comment]
At the moment this abstraction is implemented, working. It has so long never led to any issue and is live since almost the first days.

It seems that the reason we'd want to remove this model is the simplification of the architecture and models.

Maybe that changing a working software for an hypothetical simpler version is not time well spent.

Should we close this until we encounter a real reason for a change?

**Comment by oskarrough** [comment]
Hi, yes let's close. The real reason would be that we do not delete old images on Cloudinary. So if someone has uploaded 100 images, we still store all 100, but only use the latest. We can open a PR to fix that once it becomes a problem or we have time.
