### ISSUE TITLE
Rate limit

### ISSUE THREAD

**Issue by hugurp** [internet4000/radio4000-api#9]
Should we implement some kind of rate limit on the api?
Was thinking about possible abuse to it, people trying to clutter trafic or shut it down.
Minds?

**Comment by hellerve** [comment]
It completely depends. DoS attacks will and can always happen, either through ratelimiting or just flooding your service. Through ratelimiting you can at least keep your costs down.

My suggestion would be to implement toggleable ratelimiting, i.e. adding the capability to switch it on when needed, so that if you get attacked, you are able to react through ratelimiting.

**Comment by hugurp** [comment]
closed by #20
